import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { FooterComp } from '@/components/Footer';
import StoreProvider from './StoreProvider';
import { NavbarComp } from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NavbarComp />
          {children}
          <FooterComp />
        </StoreProvider>
      </body>
    </html>
  );
}
