import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { FooterComp } from '@/components/Footer';
import StoreProvider from './StoreProvider';
import Navbar from '@/components/Navbar';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Navbar />
          {children}
          <Toaster duration={1500} expand={false} richColors position='top-right'/>
          <FooterComp />
        </StoreProvider>
      </body>
    </html>
  );
}
